### ISSUE TITLE
Low power mining

### ISSUE THREAD

**Issue by informaticaeelectronica** [nicehash/NiceHashMiner2#118]
Hi,
I have dificult to have a good profit with my pool.
I have this hardware:
2x AMD RX 560
1X AMD RX550
1X AMD HD6670
1X AMD HD6310
1X AMD HD7340
And i only get 2USD per day.
Why?

**Comment by Cryptominer937** [comment]
Sounds about right for that old, Low speed equipment.

**Comment by informaticaeelectronica** [comment]
Old hardware? I had 2X RX560 and 1X RX550 its a new hardware and can do more or less 4USD per day. Only with tree GPUS...

**Comment by Crypto-Lord** [comment]
How many GB do the cards have? Is it the 2GB model or 4GB? (makes a difference for profitability) 
Also hows the setup for keeping things cool?
Have you adjusted any of the GPU settings?

**Comment by informaticaeelectronica** [comment]
Hi,
All of them have 2GB.
How i can ajust the GPU settings on NiceHashMiner?

**Comment by Crypto-Lord** [comment]
Can't adjust GPU settings in NHM, I use MSI Afterburner for that. (but not worth it with 2GB cards)

But 2GB cards are really no good at making a profit at mining. From reading on ether forums '2GB cards have become obsolete due to size of the DAG already over 2GB'

If you had the 4GB cards you could bring in ~$1-$1.25/ day, I can only assume you'd be getting about half that with 2GB cards. So your $2/day profit is bang on for your setup.

**Comment by S74nk0** [comment]
This issue is not related to NiceHash Miner program (**bugs**, **feature requests**,... ). Please use GitHub only for **bug reports** and **feature requests**. For discussions go to https://www.reddit.com/r/NiceHash/

Closing issue...
