### ISSUE TITLE
excavator hangs - 2.0.0.8

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner2#124]
It seems excavator started to hang once the ccminer miner started

![image](https://user-images.githubusercontent.com/19168174/27981557-a0a691de-635b-11e7-8353-4fb3ea194c6e.png)

**Comment by billmcilhargey** [comment]
i closed excavator and it reopened and seems to not go anywhere, if dual mining is being attempted  excavator is not liking it when another miner is using the nvidia gpu threads

![image](https://user-images.githubusercontent.com/19168174/27981594-58fa3132-635c-11e7-94bb-8d8a515b3d2d.png)

**Comment by S74nk0** [comment]
This issue is more for the [excavator issues page](https://github.com/nicehash/excavator/issues). But the upcoming nhm v2.0.0.9 will use only excavator for NVIDIA mining. 

I will close this issue as only *excavator* will be used with future nhm v2 versions (feel free to open an issue to [excavator issues page](https://github.com/nicehash/excavator/issues) if you believe this needs to be addressed)
Closing issue...
