### ISSUE TITLE
Excavator 2.0.0.8 Issue

### ISSUE THREAD

**Issue by Cryptominer937** [nicehash/NiceHashMiner2#130]
Gtx 1070 rig, if thread exits miner shuts down the api but is not being restarted. Same issue as from 2.0.0.7

**Comment by Cryptominer937** [comment]
Appears to be similar to the issue from 2.0.0.7 were cuda crashes and NHM2 is not attempting to restart excavator when hashrate drops to 0.

**Comment by Cryptominer937** [comment]
![2 0 0 8 error](https://user-images.githubusercontent.com/28938583/28140724-891eecbc-6727-11e7-82a4-08d6048693b0.png)

This is the error, Had 3 gtx 1070,s offline for 8 hrs and had no clue. Switching them over to EWBF, Genoil Ethminer which run for weeks without error for now.

**Comment by S74nk0** [comment]
This issue was due to NVIDIA miner mixing and excavator not being restarted (related [issue](https://github.com/nicehash/NiceHashMiner2/issues/124)). Please try using the current latest version v2.0.0.11 there is only excavator for NVIDIA and this issue with other miner switching will never happen (unless you are running some miner manually on the side). When using only excavator with NVIDIA devices there are no restarts needed and the miner will work as expected.

Closing issue...
