### ISSUE TITLE
Nicehash v2 and NiceHashMiner_v1.7.5.13 cant detect virtual CPU

### ISSUE THREAD

**Issue by cruerboyz** [nicehash/NiceHashMiner2#137]
Hi, i run the nicehash on my server..
i got 2 physical cpu and 8 virtual..
but after run nicehash its only detect 2 cpu only..
i already download 
https://github.com/nicehash/NiceHashMiner2/releases/download/bins/NewCPUDetection.zip and run but got error.
![capture1](https://user-images.githubusercontent.com/20983030/28395467-eb3a9216-6d26-11e7-97e7-ffec0ce2e995.PNG)

can u help me on how to configure nicehash detect all my cpu..
Thankz
![capture](https://user-images.githubusercontent.com/20983030/28395411-5fe7619e-6d26-11e7-99fd-e587c9fd2d62.PNG)

**Comment by S74nk0** [comment]
@cruerboyz In order to fix this issue install [Visual C++ Redistributable Packages for Visual Studio 2013 x68](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (it is important you install **x86**) and this issue will be resolved. This will not be needed in the new upcoming version of NHM v2.0.0.9 as this has been changed.

Closing...
Reopen issue if the suggested fix doesn't work for you
