### ISSUE TITLE
[v2.0.0.5 - FIXED] Multiple miners running at once with "Start mining" button.

### ISSUE THREAD

**Issue by Faux-Grey** [nicehash/NiceHashMiner2#2]
Nicehash Miner 2.0.0.3 - After initial setup, you're able to click the "start" button multiple times, each time it will open a new instance of the back-end miner.

Suggestion:
Should we not have the "start mining" button replaced by a "stop" button once clicked?

Edit:
This seems to only affect the first run.

After initial setup, if you do not click "start mining now" on the setup tooltip on the bottom, and instead click "Start" at the top it allows you to begin as many instances as you can click.

**Comment by S74nk0** [comment]
@Faux-Grey Start spamming should be fixed in v2.0.0.4. Please confirm this.
Expect a update notice in your NHM2 client or download the new version manually (keep link private please).

![update_example](https://cloud.githubusercontent.com/assets/1517233/26465676/5ffd44fc-418c-11e7-96f1-52e705b2dddd.PNG)

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
