### ISSUE TITLE
1080Ti mining two algorithms at once

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner2#50]
Is it intended for the 1080TI (GPU1) to run EQM and Lyra2REv2 at the same time? This is 2.0.0.5

![image](https://cloud.githubusercontent.com/assets/20034137/26595502/99cb3d50-4539-11e7-987e-1361f8dc37e6.png)

**Comment by ChriscomIT** [comment]
No this seems to be a bug with the v2.0.0.5 and I have the same. Also at startup excavator cmd initializes and don't close itself. Excavator cmd window stays up and even instantly restarting when closed manually.

Therefore excavator also doesn't close itself when the miner is switching algorithms and stays up/is mining forever. That's why u see "correctly" 3 algorithms in the GUI which be mined on. Not normal behavior.

This was more or less already reported in this issue: #49 .

**Comment by meepominer** [comment]
same issue here, i have to manually disable all algorithms except the one i want to keep.

**Comment by felixbrucker** [comment]
same here: 
![image](https://cloud.githubusercontent.com/assets/5189997/26774837/78415488-49d2-11e7-9b47-c307b69c1b67.png)

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.6 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.6 Alpha**
