### ISSUE TITLE
NiceHashMiner2 will be Open Source?

### ISSUE THREAD

**Issue by augustresende** [nicehash/NiceHashMiner2#63]
NiceHashMiner2 will be Open Source?
@S74nk0 @nicehashdev

**Comment by nicehashdev** [comment]
No.

**Comment by augustresende** [comment]
Why?

**Comment by Cryptominer937** [comment]
Because Nicehash has switched gears from just using open source programs to paying in house developers making the software private as compared to open source which is fine seeing as how they are not limiting their miners to only run on their pools and they operate fee free. now Nicehash Miner is designed to work with their servers only hence it being called Nicehash Miner and not public mining optimizer.
