### ISSUE TITLE
[v2.0.0.8 - FIXED] "MinimizeToTray": true doesn't work

### ISSUE THREAD

**Issue by coinbutter** [nicehash/NiceHashMiner2#65]
Setting `"MinimizeToTray": true` in `General.json` doesn't make NHM2 minimize to tray.

**Comment by cpshoemake** [comment]
I've noticed the same thing on my 3 workers.

**Comment by ChriscomIT** [comment]
Did u check the edited config file was still edited after saving and running NHM v2? You have to close the app before saving the edited config file or all values are reverted to the old ones.

**Comment by coinbutter** [comment]
Yes, I verified that the config hadn't changed after my edit.

**Comment by ChriscomIT** [comment]
That's why you need to close the GUI BEFORE saving the edited config file. If not all values remain the old. For me it's working.

**Comment by coinbutter** [comment]
I'm glad that it's working for you and that you know where your caps-lock key is. I apologize that I mistook your first message as being from someone who was being helpful and responding in kind by answering your question. But to answer the question you didn't ask, the first time I edited the configuration file NHM2 was still running and it reverted after I closed NHM2 so I edited it while it was closed and the change hasn't reversed despite restarting NHM2 a number of times.

**Comment by ChriscomIT** [comment]
Kool thanks for the confirmation so this is actually a bug. Sorry, it seems I did misread your first answer and apologizing for that. I tried to be helpful to you but mostly for the devs in confirming its a new bug. BTW it wasn't even caps lock. Don't know why you got offended now? But whatever suits you. Have a nice day with this fine attitude.

**Comment by coinbutter** [comment]
I'm not offended, I just don't appreciate being treated like I'm stupid BEFORE... after I answered your question. I'm certain that you wouldn't appreciate being treated that way either. And I responded today because that is when I got back to my desk.

**Comment by ChriscomIT** [comment]
Oh man, you have some serious problems that are sure, no one treated you like you are or said you are stupid. I just asked this twice because I did misread your first answer which I have apologized here.
And I did highlight that fact first because of this and as well because it's a known problem since the first release (which will be worked on) and I wanted to make sure it's not the same issue and also provide a solution for you if it's not a new issue.

And honestly, I don't care or judge you in any way from when you are at your desk or replying. I get a slight feeling that you maybe did misread my answer as well ??

However GitHub is the wrong place for this super duper nice useless discussion, so I am back off from here and apologizing once again for all the bad moods and feelings I did give you with my message.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
