### ISSUE TITLE
Feature Request: Community Translations

### ISSUE THREAD

**Issue by augustresende** [nicehash/NiceHashMiner2#94]

**Comment by S74nk0** [comment]
@AugustoResende this was considered before. But because we cannot verify the translations ourselves (since we do not understand them) it can be easy for anyone to write **inaccurate** or **offensive** content. Because of this we do not include community translations in the releases (v1 nor v2). We might reconsider including them in the future, but I doubt we will.
Closing...

**Comment by augustresende** [comment]
google translator used for what?
